### ISSUE TITLE
Tag-based API?

### ISSUE THREAD

**Issue by konsvoulg** [teleconsys/inx-collector#11]
Hello!

Based on a conversation we had through email on the specific suggestion, would it be possible to implement an additional API to retrieve the stored data blocks (Block IDs) based on their assigned tag? It would be really useful, and in my personal opinion, logical, since there is also a mode within the collector to listen to blocks with specific tags.

**Comment by Giordyfish** [comment]
This feature might be handy and may be added in future. 

In the meantime, you can achieve an equivalent behaviour by creating a bucket in your S3 storage dedicated to a single tag you want to subscribe to. Then you can create a filter for that tag and specify the newly created bucket in the `BucketName` field of the filter (you could name your bucket as the tag for example). 

You should now be able to use your storage's APIs to access all objects in the specific tag's bucket. This way you can be sure you are only getting blocks with the tag you want.

**Comment by konsvoulg** [comment]
I see. Indeed, it sounds like an alternative solution. However, will we be able to do that through an external device outside the local network? For example, if the node and bucket are running locally on a stationary RPi device and the user is located in a remote location and wants to retrieve the blocks by accessing the bucket through his laptop. Will they be able to follow that process with the minio's API? I mainly ask that question for those of us that are not familiar with S3 storages, or minio specifically. 

That's why I suggested the collector API approach. because in the case of a Hornet node running with HTTPS configuration, which is really useful for running IoT applications, it's way easier to interact with it through the node's domain and its respective APIs, without location restrictions. I'm not sure if it makes sense the way I described it.

**Comment by Giordyfish** [comment]
Of course you can. You can modify the `docker-compose.yml` file to expose the port where minio's API server is running (you can read more about APIs in minio documentation) and then access it the same way you would with your hornet node, by specifying its port. Then you can use APIs, or any of the provided SDKs to get all objects in the bucket (S3 storages should have at least have an API to list all objects in a bucket and one to get an object, so you can iterate the `GET` part on the list).

You are not even limited to use minio as a storage, you could use any other S3 storage. 
You could also have your S3 storage somewhere else and have Collector push blocks there (look at the parameters you can set to configure your storage). You can then access this remote repository from everywhere. 

If you work with the storage you can do whatever you want. Whereas, implementing a new API route has some issue which require more thought. Collector doesn't enforce you to have a single bucket, so you should have access to all storage's bucket to look for specific tags, which make it so you can't even have different access policies in the same storage space, this is not something that Collector should impose. Even if you limit the feature to a single bucket, in the most general case, S3 storage itself cannot know what's the tag of a block as it sees it as a simple object. This means that you must either add some kind of logic to the collector that download all blocks from the storage and then check which to forward to the client and which not (that's quite inefficient), or use additional fields like metadata or anything with tag-like behaviour. 

I encourage you to try to customize your storage interaction, as it will be the most flexible and future-proof solution to your issue.

**Comment by konsvoulg** [comment]
Sorry for the later reply. I did it the way you described it. Exposed the ports and interacted with the minio APIs exclusively to retrieve the data.
